# Generated by Django 3.2.18 on 2023-03-22 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество не меньше 1')], verbose_name='количество ингредиента')),
            ],
            options={
                'verbose_name': 'количество ингредиента в рецепте',
                'ordering': ('ingredient',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название ингредиента')),
                ('measurement_unit', models.CharField(max_length=50, verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование рецепта', max_length=200, verbose_name='наименование рецепта')),
                ('image', models.ImageField(help_text='Загрузите изображение рецепта', upload_to='recipes_img/', verbose_name='изображение к рецепту')),
                ('text', models.TextField(help_text='Содержание рецепта', verbose_name='текст рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Время приготовления в минутах', verbose_name='время приготовления блюда по рецепту')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Введите цвет тега', max_length=7, unique=True, verbose_name='цветовой HEX-код тега')),
                ('name', models.CharField(help_text='Введите название тега', max_length=30, unique=True, verbose_name='название')),
                ('slug', models.SlugField(help_text='Введите уникальный адрес', max_length=200, unique=True, verbose_name='уникальный адрес')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
                'ordering': ('name',),
            },
        ),
    ]
