# Generated by Django 3.2.18 on 2023-03-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountofingredient',
            options={'ordering': ('ingredient',), 'verbose_name': 'количество ингредиента в рецепте '},
        ),
        migrations.AlterField(
            model_name='amountofingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение рецепта', upload_to='recipes_img/%Y/%m/', verbose_name='изображение к рецепту'),
        ),
    ]
