# Generated by Django 3.2.18 on 2023-03-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_recipe_name_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountofingredient',
            name='unique_amount_ingredient',
        ),
    ]
