# Generated by Django 3.2.18 on 2023-04-12 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_amountofingredient_unique_amount_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.ingredient', validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество не меньше 1')], verbose_name='название ингредиента'),
        ),
    ]
