# Generated by Django 3.2.18 on 2023-03-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique follower_author',
        ),
    ]
